package id.alphamedia.lkki.models;

import java.util.Date;

import io.realm.RealmObject;
import io.realm.annotations.Index;
import io.realm.annotations.PrimaryKey;
import io.realm.annotations.Required;

/**
 * Created by abdulmuin on 12/07/17.
 */

public class DataProspek extends RealmObject  {

    // @PrimaryKey
    private long id_prospek;

    // private long id_prospek = PrimaryKeyFactory.nextKey(DataProspek.class);


    @PrimaryKey
    @Required
    @Index
    private String uuid;

    /*
    * tambahkan String id_koor_wil, id_ma_wil,
    * */

    // catatan status
    private int status_prospek;

    private int uid;

    private boolean status_koor, status_ma, status_presentasi;

    private String catatan, nik_pencatat, nama_pencatat;

    private String tempat, nama, jalan, kelurahan, imei, email, rt;
    private String rw, no_hp, no_kantor, lokasi_lat, lokasi_long;
    private String kata_kunci, provinsi, kota, kecamatan, desa, jabatan;

    // tanggal pencatatan
    private Date tgl_catat;
    private Date tgl_penyuluhan;
    private String waktu_penyuluhan;
    private int durasi;

    // konsultan penyuluh
    private String konsultan1, konsultan2;

    // status data dikirim ke server
    private boolean is_dikirim;
    private Date tgl_dikirim;

    private int kurir, jmlorder;
    private String kurir_tgl_kirim;

    public DataProspek(){
    }

    // Standard getters & setters generated by your IDE…
    public String getUuid() { return uuid; }
    // UUID.randomUUID().toString();
    public void setUuid(String uuid) { this.uuid = uuid; }
    public void setId_prospek(long id) { this.id_prospek = id;}
    public Long getId_prospek(){ return id_prospek; }
    public String getNama() { return nama; }
    public void setNama(String nama) { this.nama = nama; }
    public void setJalan(String jalan) { this.jalan = jalan; }
    public void setKelurahan(String kelurahan) { this.kelurahan = kelurahan; }
    public void setImei(String imei) { this.imei = imei; }
    public void setTempat(String tempat) { this.tempat = tempat; }
    public String getTempat() { return tempat; }
    public String getJalan() { return jalan; }
    public String getKelurahan() { return kelurahan; }
    public String getImei() { return imei; }
    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }
    public String getRt() { return rt; }
    public void setRt(String rt) {this.rt = rt; }
    public String getRw() { return rw; }
    public void setRw(String rw) {this.rw = rw; }
    public String getNo_hp() { return no_hp; }
    public void setNo_hp(String no_hp) { this.no_hp = no_hp; }
    public String getNo_kantor() { return no_kantor; }
    public void setNo_kantor(String no_kantor) { this.no_kantor = no_kantor; }
    public String getLokasi_lat() { return lokasi_lat; }
    public void setLokasi_lat(String lokasi_lat) { this.lokasi_lat = lokasi_lat; }
    public String getLokasi_long() { return lokasi_long; }
    public void setLokasi_long(String lokasi_long) { this.lokasi_long = lokasi_long; }
    public String getKata_kunci() { return kata_kunci; }
    public void setKata_kunci(String kata_kunci) { this.kata_kunci = kata_kunci; }
    public String getProvinsi() { return provinsi; }
    public void setProvinsi(String provinsi) { this.provinsi = provinsi; }
    public String getKota() { return kota; }
    public void setKota(String kota) { this.kota = kota; }
    public String getKecamatan() { return kecamatan; }
    public void setKecamatan(String kecamatan) { this.kecamatan = kecamatan; }
    public String getDesa() { return desa; }
    public void setDesa(String desa) { this.desa = desa; }
    public void setJabatan(String jabatan) { this.jabatan = jabatan; }
    public String getJabatan() { return jabatan; }
    public Date getTgl_penyuluhan(){ return tgl_penyuluhan; }
    public void setTgl_penyuluhan(Date tgl_penyuluhan) { this.tgl_penyuluhan = tgl_penyuluhan; }

    public void setCatatan(String catatan_status) { this.catatan = catatan_status; }
    public String getCatatan(){ return catatan; }

    public void setStatus_prospek(int status_prospek){ this.status_prospek = status_prospek; }
    public int getStatus_prospek() { return status_prospek; }

    public void setTgl_catat(Date tgl_catat) { this.tgl_catat = tgl_catat; }
    public Date getTgl_catat() { return tgl_catat; }

    public void setWaktu_penyuluhan(String waktu_penyuluhan){ this.waktu_penyuluhan = waktu_penyuluhan; }
    public String getWaktu_penyuluhan() { return waktu_penyuluhan; }

    public void setDurasi(int durasi) { this.durasi = durasi; }
    public int getDurasi() { return durasi; }

    public void setIs_dikirim(boolean is_dikirim) { this.is_dikirim = is_dikirim; }
    public boolean isIs_dikirim(){ return is_dikirim; }
    public boolean getIs_dikirim(){ return is_dikirim; }

    public void setTgl_dikirim(Date tgl_dikirim) { this.tgl_dikirim = tgl_dikirim; }
    public Date getTgl_dikirim(){ return tgl_dikirim; }

    public void setStatus_koor(boolean status_koor){
        this.status_koor = status_koor;
    }

    public boolean isStatus_koor(){
        return status_koor;
    }

    public void setStatus_ma(boolean status_ma){
        this.status_ma = status_ma;
    }

    public boolean isStatus_ma(){
        return status_ma;
    }

    public void setStatus_presentasi(boolean status_presentasi){
        this.status_presentasi = status_presentasi;
    }

    public boolean isStatus_presentasi(){
        return status_presentasi;
    }

    public String getNik_pencatat(){
        return nik_pencatat;
    }

    public void setNik_pencatat(String nik_pencatat){
        this.nik_pencatat = nik_pencatat;
    }

    public String getNama_pencatat(){
        return nama_pencatat;
    }

    public void setNama_pencatat(String nama_pencatat){
        this.nama_pencatat = nama_pencatat;
    }

    public void setUid(int uid){ this.uid = uid; }
    public int getUid(){ return uid; }

    public void setKonsultan1(String konsultan1){ this.konsultan1 = konsultan1; }
    public String getKonsultan1(){ return konsultan1; }

    public void setKonsultan2(String konsultan2) { this.konsultan2 = konsultan2; }
    public String getKonsultan2(){ return konsultan2; }

    public void setKurir(int kurir) { this.kurir = kurir; }
    public int getKurir() { return kurir; }

    public void setJmlorder(int jmlorder){ this.jmlorder = jmlorder; }
    public int getJmlorder(){ return jmlorder; }

    public void setKurir_tgl_kirim(String kurir_tgl_kirim){
        this.kurir_tgl_kirim = kurir_tgl_kirim;
    }

    public String getKurir_tgl_kirim(){
        return kurir_tgl_kirim;
    }

}

